services:
  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    depends_on:
    - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
    - .env
    networks:
    - inception
    restart: always

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    volumes:
    - mariadb_data:/var/lib/mysql
    networks:
    - inception
    restart: always

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    depends_on:
    - wordpress
    volumes:
    - wordpress_data:/var/www/html
    ports:
    - "443:443"
    networks:
    - inception
    restart: always

volumes:
  wordpress_data:
  driver: local
  driver_opts:
  type: 'none'
  o: 'bind
  device: Users/tpotilli/data/wordpress

mariadb:
  driver: local
  driver_opts:
  type: 'none'
  o: 'bind'
  device: Users/tpotilli/data/mariadb

networks:
  inception:
    driver: bridge